#!/usr/bin/env python3
"""Train and evaluate a reconstruction-based anomaly model for one windowed config.

This script is reusable across run folders generated by windowed_time_split.py.

Expected files in --run-dir:
- windowed_train.csv
- windowed_val.csv
- windowed_test.csv

Outputs in --run-dir/model:
- scaler.joblib
- autoencoder.joblib
- threshold.json
- eval_report.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler


META_COLS = {
    "source",
    "start_index",
    "end_index",
    "start_ts",
    "end_ts",
    "anomaly_fraction",
    "window_label",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train one window-config anomaly model from a run folder"
    )
    parser.add_argument(
        "--run-dir",
        required=True,
        help="Folder containing windowed_train.csv, windowed_val.csv, windowed_test.csv",
    )
    parser.add_argument(
        "--label-col",
        default="window_label",
        help="Label column name (default: window_label)",
    )
    parser.add_argument(
        "--threshold-percentile",
        type=float,
        default=99.0,
        help="Percentile on validation normal errors for threshold calibration",
    )
    parser.add_argument(
        "--hidden-layers",
        default="256,128,256",
        help="Comma-separated hidden layer sizes for MLP autoencoder",
    )
    parser.add_argument(
        "--max-iter",
        type=int,
        default=200,
        help="Maximum iterations for MLPRegressor",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed",
    )
    return parser.parse_args()


def parse_hidden_layers(text: str) -> tuple[int, ...]:
    parts = [p.strip() for p in text.split(",") if p.strip()]
    if not parts:
        raise ValueError("--hidden-layers must contain at least one integer")
    layers = tuple(int(p) for p in parts)
    if any(v <= 0 for v in layers):
        raise ValueError("hidden layer sizes must be positive")
    return layers


def load_split(path: Path, label_col: str) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Missing split file: {path}")
    df = pd.read_csv(path)
    if label_col not in df.columns:
        raise ValueError(f"Missing label column '{label_col}' in {path}")
    return df


def select_feature_cols(df: pd.DataFrame, label_col: str) -> list[str]:
    cols: list[str] = []
    for c in df.columns:
        if c == label_col:
            continue
        if c in META_COLS:
            continue
        cols.append(c)
    if not cols:
        raise ValueError("No feature columns found after excluding metadata")
    return cols


def reconstruction_error(y_true: np.ndarray, y_pred: np.ndarray) -> np.ndarray:
    # Mean squared error per row.
    return np.mean((y_true - y_pred) ** 2, axis=1)


def compute_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> dict[str, float | list[list[int]]]:
    precision = precision_score(y_true, y_pred, zero_division=0)
    recall = recall_score(y_true, y_pred, zero_division=0)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])

    tn, fp, fn, tp = cm.ravel()
    fpr = float(fp / (fp + tn)) if (fp + tn) > 0 else 0.0

    return {
        "precision": float(precision),
        "recall": float(recall),
        "f1": float(f1),
        "false_positive_rate_normal": float(fpr),
        "confusion_matrix_labels_0_1": cm.tolist(),
        "tn": int(tn),
        "fp": int(fp),
        "fn": int(fn),
        "tp": int(tp),
    }


def main() -> None:
    args = parse_args()

    run_dir = Path(args.run_dir)
    train_path = run_dir / "windowed_train.csv"
    val_path = run_dir / "windowed_val.csv"
    test_path = run_dir / "windowed_test.csv"

    train_df = load_split(train_path, args.label_col)
    val_df = load_split(val_path, args.label_col)
    test_df = load_split(test_path, args.label_col)

    feature_cols = select_feature_cols(train_df, args.label_col)

    for name, df in [("val", val_df), ("test", test_df)]:
        missing = [c for c in feature_cols if c not in df.columns]
        if missing:
            raise ValueError(f"{name} split missing feature columns: {missing[:10]}")

    train_df = train_df.dropna(subset=feature_cols + [args.label_col]).copy()
    val_df = val_df.dropna(subset=feature_cols + [args.label_col]).copy()
    test_df = test_df.dropna(subset=feature_cols + [args.label_col]).copy()

    train_labels = pd.to_numeric(train_df[args.label_col], errors="coerce").astype(int).to_numpy()
    val_labels = pd.to_numeric(val_df[args.label_col], errors="coerce").astype(int).to_numpy()
    test_labels = pd.to_numeric(test_df[args.label_col], errors="coerce").astype(int).to_numpy()

    x_train_all = train_df[feature_cols].to_numpy(dtype=np.float32)
    x_val = val_df[feature_cols].to_numpy(dtype=np.float32)
    x_test = test_df[feature_cols].to_numpy(dtype=np.float32)

    x_train_normal = x_train_all[train_labels == 0]
    if len(x_train_normal) == 0:
        raise ValueError("No normal (label 0) windows in train split")

    scaler = StandardScaler()
    x_train_normal_scaled = scaler.fit_transform(x_train_normal)
    x_val_scaled = scaler.transform(x_val)
    x_test_scaled = scaler.transform(x_test)

    hidden_layers = parse_hidden_layers(args.hidden_layers)
    model = MLPRegressor(
        hidden_layer_sizes=hidden_layers,
        activation="relu",
        solver="adam",
        max_iter=args.max_iter,
        random_state=args.seed,
        early_stopping=True,
        validation_fraction=0.1,
        n_iter_no_change=10,
        verbose=False,
    )

    model.fit(x_train_normal_scaled, x_train_normal_scaled)

    val_pred = model.predict(x_val_scaled)
    test_pred = model.predict(x_test_scaled)

    val_err = reconstruction_error(x_val_scaled, val_pred)
    test_err = reconstruction_error(x_test_scaled, test_pred)

    val_normal_err = val_err[val_labels == 0]
    if len(val_normal_err) == 0:
        val_normal_err = val_err

    threshold = float(np.percentile(val_normal_err, args.threshold_percentile))

    val_pred_labels = (val_err > threshold).astype(int)
    test_pred_labels = (test_err > threshold).astype(int)

    val_metrics = compute_metrics(val_labels, val_pred_labels)
    test_metrics = compute_metrics(test_labels, test_pred_labels)

    model_dir = run_dir / "model"
    model_dir.mkdir(parents=True, exist_ok=True)

    scaler_path = model_dir / "scaler.joblib"
    model_path = model_dir / "autoencoder.joblib"
    threshold_path = model_dir / "threshold.json"
    report_path = model_dir / "eval_report.json"

    joblib.dump(scaler, scaler_path)
    joblib.dump(model, model_path)

    threshold_payload = {
        "threshold": threshold,
        "threshold_percentile": args.threshold_percentile,
        "val_normal_error_mean": float(np.mean(val_normal_err)),
        "val_normal_error_std": float(np.std(val_normal_err)),
        "feature_count": len(feature_cols),
    }
    threshold_path.write_text(json.dumps(threshold_payload, indent=2), encoding="utf-8")

    report = {
        "run_dir": str(run_dir),
        "train_rows": int(len(train_df)),
        "val_rows": int(len(val_df)),
        "test_rows": int(len(test_df)),
        "train_normal_rows": int((train_labels == 0).sum()),
        "feature_count": len(feature_cols),
        "feature_columns": feature_cols,
        "model": {
            "type": "MLPRegressor_autoencoder",
            "hidden_layers": list(hidden_layers),
            "max_iter": args.max_iter,
            "random_seed": args.seed,
        },
        "threshold": threshold_payload,
        "validation_metrics": val_metrics,
        "test_metrics": test_metrics,
    }
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")

    print("Training complete")
    print(f"run_dir={run_dir}")
    print(f"features={len(feature_cols)}")
    print(f"threshold={threshold:.8f}")
    print(f"test_f1={test_metrics['f1']:.6f}")
    print(f"test_precision={test_metrics['precision']:.6f}")
    print(f"test_recall={test_metrics['recall']:.6f}")
    print(f"test_fpr_normal={test_metrics['false_positive_rate_normal']:.6f}")
    print(f"model_dir={model_dir}")


if __name__ == "__main__":
    main()
